"""add common_test_rank to loinc_codes

Revision ID: 302898ee8a21
Revises: 3c23182bed6b
Create Date: 2026-09-27 02:41:51.258774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302898ee8a21'
down_revision: Union[str, None] = '3c23182bed6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # loinc_codes already has ~62k existing rows in any deployed environment,
    # so a NOT NULL column needs a server_default -- otherwise Postgres
    # rejects the ALTER TABLE outright (SQLite is lenient about this, which
    # is how the plain autogenerated version passed locally but would have
    # broken the real deploy target).
    op.add_column(
        "loinc_codes",
        sa.Column("common_test_rank", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loinc_codes', 'common_test_rank')
    # ### end Alembic commands ###
