"""initial schema

Revision ID: 3c23182bed6b
Revises: 
Create Date: 2026-09-27 02:41:38.104895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c23182bed6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='documentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loinc_codes',
    sa.Column('loinc_num', sa.String(length=32), nullable=False),
    sa.Column('long_common_name', sa.String(length=512), nullable=False),
    sa.Column('shortname', sa.String(length=256), nullable=True),
    sa.Column('component', sa.String(length=256), nullable=True),
    sa.Column('property', sa.String(length=64), nullable=True),
    sa.Column('time_aspect', sa.String(length=64), nullable=True),
    sa.Column('system', sa.String(length=128), nullable=True),
    sa.Column('scale_type', sa.String(length=64), nullable=True),
    sa.Column('method_type', sa.String(length=128), nullable=True),
    sa.Column('class', sa.String(length=128), nullable=True),
    sa.Column('example_units', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('loinc_num')
    )
    op.create_table('loinc_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loinc_num', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['loinc_num'], ['loinc_codes.loinc_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('original_test_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_test_name', sa.String(length=512), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('reference_range', sa.String(length=128), nullable=True),
    sa.Column('specimen', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=256), nullable=True),
    sa.Column('timing', sa.String(length=128), nullable=True),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('loinc_code', sa.String(length=32), nullable=True),
    sa.Column('loinc_display', sa.String(length=512), nullable=True),
    sa.Column('mapping_status', sa.Enum('confirmed', 'needs_review', 'unmapped', name='mappingstatus'), nullable=False),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('mapping_stage', sa.String(length=32), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('raw_extraction', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('loinc_aliases')
    op.drop_table('loinc_codes')
    op.drop_table('documents')
    # ### end Alembic commands ###
